/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateProductCommand } from '../../models/create-product-command';
import { GuidApiResponse } from '../../models/guid-api-response';

export interface ApiProductsPost$Params {
      body: CreateProductCommand
}

export function apiProductsPost(http: HttpClient, rootUrl: string, params: ApiProductsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<GuidApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiProductsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuidApiResponse>;
    })
  );
}

apiProductsPost.PATH = '/api/products';
