/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCustomerCommand } from '../../models/create-customer-command';
import { GuidApiResponse } from '../../models/guid-api-response';

export interface ApiCustomersPost$Params {
      body: CreateCustomerCommand
}

export function apiCustomersPost(http: HttpClient, rootUrl: string, params: ApiCustomersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<GuidApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCustomersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuidApiResponse>;
    })
  );
}

apiCustomersPost.PATH = '/api/customers';
