/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiResponse } from './models/api-response';
export type { CreateCategoryCommand } from './models/create-category-command';
export type { CreateCustomerCommand } from './models/create-customer-command';
export type { CreateOrderCommand } from './models/create-order-command';
export type { CreateOrderDetailDto } from './models/create-order-detail-dto';
export type { CreateProviderCommand } from './models/create-provider-command';
export type { Gender } from './models/gender';
export type { GuidApiResponse } from './models/guid-api-response';
export type { ObjectApiResponse } from './models/object-api-response';
export type { OrderStatus } from './models/order-status';
export type { OrderType } from './models/order-type';
export type { UpdateCategoryCommand } from './models/update-category-command';
export type { UpdateCustomerCommand } from './models/update-customer-command';
export type { UpdateOrderStatusCommand } from './models/update-order-status-command';
export type { UpdateProviderCommand } from './models/update-provider-command';
export type { UpdateStockCommand } from './models/update-stock-command';
