/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiCategoriesIdGet$Params {
  id: string;
}

export function apiCategoriesIdGet(http: HttpClient, rootUrl: string, params: ApiCategoriesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCategoriesIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectApiResponse>;
    })
  );
}

apiCategoriesIdGet.PATH = '/api/categories/{id}';
