/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiWarehousesProductProductIdGet$Params {
  productId: string;
}

export function apiWarehousesProductProductIdGet(http: HttpClient, rootUrl: string, params: ApiWarehousesProductProductIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiWarehousesProductProductIdGet.PATH, 'get');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectApiResponse>;
    })
  );
}

apiWarehousesProductProductIdGet.PATH = '/api/warehouses/product/{productId}';
