/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateOrderDetailDto } from '../models/create-order-detail-dto';
import { OrderType } from '../models/order-type';
export interface CreateOrderCommand {
  code?: string | null;
  createdBy?: string | null;
  customerId?: string | null;
  details?: Array<CreateOrderDetailDto> | null;
  discount?: number;
  note?: string | null;
  orderDate?: string;
  providerId?: string | null;
  shippingFee?: number;
  type?: OrderType;
}
