/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOrderDetailDto {
  discount?: number;
  productId?: string;
  providerId?: string | null;
  quantity?: number;
  tax?: number;
  unitPrice?: number;
}
