/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCategoryCommand {
  code?: string | null;
  description?: string | null;
  icon?: string | null;
  name?: string | null;
  parentId?: string | null;
  sortOrder?: number;
}
