/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProviderCommand {
  address?: string | null;
  code?: string | null;
  contactPerson?: string | null;
  email?: string | null;
  name?: string | null;
  note?: string | null;
  phone?: string | null;
  taxCode?: string | null;
}
