/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Gender } from './gender';

/**
 * Each possible value of `Gender`
 */
export const GENDER: Gender[] = [
  1,
  2,
  3
];