/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderType } from './order-type';

/**
 * Each possible value of `OrderType`
 */
export const ORDER_TYPE: OrderType[] = [
  1,
  2
];