/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderStatus } from './order-status';

/**
 * Each possible value of `OrderStatus`
 */
export const ORDER_STATUS: OrderStatus[] = [
  0,
  1,
  2,
  3,
  4
];