/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderStatus } from '../models/order-status';
export interface UpdateOrderStatusCommand {
  id?: string;
  status?: OrderStatus;
}
