/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductCommand {
  categoryId?: string;
  code?: string | null;
  costPrice?: number;
  description?: string | null;
  id?: string;
  image?: string | null;
  isActive?: boolean;
  isNew?: boolean;
  isSale?: boolean;
  name?: string | null;
  originalPrice?: number | null;
  sellingPrice?: number;
  unit?: string | null;
}
