/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Gender } from '../models/gender';
export interface UpdateCustomerCommand {
  address?: string | null;
  code?: string | null;
  dateOfBirth?: string | null;
  email?: string | null;
  fullName?: string | null;
  gender?: Gender;
  id?: string;
  isActive?: boolean;
  note?: string | null;
  phone?: string | null;
}
