/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCategoryCommand {
  code?: string | null;
  description?: string | null;
  icon?: string | null;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  parentId?: string | null;
  sortOrder?: number;
}
