/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProviderCommand {
  address?: string | null;
  code?: string | null;
  contactPerson?: string | null;
  email?: string | null;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  note?: string | null;
  phone?: string | null;
  taxCode?: string | null;
}
