/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateStockCommand {
  id?: string;
  location?: string | null;
  maxQuantity?: number;
  minQuantity?: number;
  providerId?: string | null;
  quantity?: number;
}
