/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectApiResponse } from '../../models/object-api-response';
import { OrderType } from '../../models/order-type';

export interface ApiOrdersGet$Params {
  type?: OrderType;
}

export function apiOrdersGet(http: HttpClient, rootUrl: string, params?: ApiOrdersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiOrdersGet.PATH, 'get');
  if (params) {
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectApiResponse>;
    })
  );
}

apiOrdersGet.PATH = '/api/orders';
